import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ title }) {
  return (
    <>
      <Head>
        <title>Events App by Sika</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>

      <h1>{title}</h1>
      
      <main className={`${styles.main} ${inter.className}`}>
        <a href=''>
          <img src=''/>
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Neque veniam iusto quae dignissimos recusandae quibusdam rem quas tempore nostrum vero dolorum aspernatur doloribus commodi, odit pariatur delectus aperiam voluptatibus architecto nam placeat dolorem deserunt sit nisi natus? Optio, accusantium enim odit voluptatum repudiandae voluptatibus, repellendus iusto ipsa quaerat sit iure?</p>
        </a>
        <a href=''>
          <img src=''/>
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Neque veniam iusto quae dignissimos recusandae quibusdam rem quas tempore nostrum vero dolorum aspernatur doloribus commodi, odit pariatur delectus aperiam voluptatibus architecto nam placeat dolorem deserunt sit nisi natus? Optio, accusantium enim odit voluptatum repudiandae voluptatibus, repellendus iusto ipsa quaerat sit iure?</p>
        </a>
        <a href=''>
          <img src=''/>
          <h2>Events in Barcelona</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Neque veniam iusto quae dignissimos recusandae quibusdam rem quas tempore nostrum vero dolorum aspernatur doloribus commodi, odit pariatur delectus aperiam voluptatibus architecto nam placeat dolorem deserunt sit nisi natus? Optio, accusantium enim odit voluptatum repudiandae voluptatibus, repellendus iusto ipsa quaerat sit iure?</p>
        </a>
      </main>

      <footer>
        <p> copyright 2023. A project built usinf next.js</p>
      </footer>
    </>
  )
}


export function getServerSideProps() {
  return {
      props: {
          title: "Hello Everyone!"
      }
  }
}
